---
- name: Join additional cluster nodes
  shell: 
    "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add \
      -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} \
      --user={{ couchbase_server_admin }} \
      --password={{ couchbase_server_password }} \
      --server-add={{ hostvars[item]['ansible_'+ iface | default('eth0') ]['ipv4']['address'] }}:{{ couchbase_server_admin_port }} \
      --server-add-username={{ couchbase_server_admin }} \
      --server-add-password={{ couchbase_server_password }}"
  with_items: groups['additional']

- name: Rebalance cluster
  shell: 
    "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance \
      -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} \
      --user={{ couchbase_server_admin }} \
      --password={{ couchbase_server_password }}"
