---
- name: Get major version
  shell: cat /opt/couchbase/VERSION.txt | cut -d '.' -f1
  register: cb_major_version

- name: Wait for Admin
  wait_for: "port={{ couchbase_server_admin_port }} delay=5"

- name: Configure cluster settings
  shell: 
    "{{ couchbase_server_bin_path }}/couchbase-cli cluster-init \
      -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} \
      --cluster-username={{ couchbase_server_admin }} \
      --cluster-password={{ couchbase_server_password }} \
      --cluster-port={{couchbase_server_admin_port}} \
      --cluster-ramsize={{ couchbase_server_ram }}"
  when: cb_major_version['stdout'] != "4"
  ignore_errors: true

- name: Wait for Admin
  wait_for: "port={{ couchbase_server_admin_port }} delay=5"

- name: Initialize node
  shell: 
    "{{ couchbase_server_bin_path }}/couchbase-cli node-init \
      -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} \
      --username={{ couchbase_server_admin }} \
      --password={{ couchbase_server_password }} \
      --node-init-hostname={{ couchbase_server_node }}"
  when: cb_major_version['stdout'] != "2"
  ignore_errors: true