---
- name: Verify node health
  shell: 
    "{{ couchbase_server_bin_path }}/couchbase-cli server-list \
      -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} \
      --user={{ couchbase_server_admin }} \
      --password={{ couchbase_server_password }} \
      | awk '/{{ couchbase_server_node }}:{{ couchbase_server_admin_port }}/ {print $3}'"
  register: couchbase_server_health
  failed_when: couchbase_server_health['stdout'] != "healthy"

- name: Create new bucket
  shell: 
    "{{ couchbase_server_bin_path }}/couchbase-cli bucket-create \
      -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} \
      --user={{ couchbase_server_admin }} \
      --password={{ couchbase_server_password }} \
      --bucket={{ item.name }} \
      --bucket-type={{ couchbase_server_bucket_type }} \
      --bucket-port={{ couchbase_server_bucket_port }} \
      --bucket-ramsize={{ item.ram }} \
      --bucket-replica={{ item.replica }}"
  when: couchbase_server_health['stdout'] == "healthy"
  with_items:
    couchbase_buckets
