---
- include: cluster_install.yml
  when: couchbase_cluster_install

- include: cluster_init.yml
  when: couchbase_cluster_init

- include: cluster_add_rebalance.yml
  when: couchbase_cluster_add_rebalance

- include: cluster_create_bucket.yml
  when: couchbase_create_bucket