---
- include: cluster_install.yml
  when: couchbase_cluster_install

- include: cluster_init_primary.yml
  when: couchbase_cluster_init_primary

- include: cluster_init_additional.yml
  when: couchbase_cluster_init_additional

- include: cluster_add_rebalance.yml
  when: couchbase_cluster_add_rebalance

- include: cluster_create_bucket.yml
  when: couchbase_create_bucket